version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.1-alpine
    container_name: nmdr-db
    environment:
      POSTGRES_USER: dhis
      POSTGRES_PASSWORD: dhis
      POSTGRES_DB: dhis2
      POSTGRES_INITDB_ARGS: "-c shared_buffers=256MB -c max_locks_per_transaction=100"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dhis"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nmdr-network
    restart: unless-stopped

  nmdr:
    build: .
    image: nmdr:latest
    container_name: nmdr-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DHIS2_HOME: /opt/dhis2
      JAVA_OPTS: "-Xms2000m -Xmx4000m"
    volumes:
      - nmdr-files:/opt/dhis2/files
      - nmdr-apps:/opt/dhis2/apps
    networks:
      - nmdr-network
    restart: unless-stopped

volumes:
  db-data:
    driver: local
  nmdr-files:
    driver: local
  nmdr-apps:
    driver: local

networks:
  nmdr-network:
    driver: bridge
